# Generated by Django 4.2.24 on 2025-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(help_text='Use a strong password with at least 8 characters.', max_length=128, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user can log in.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
            ],
            options={
                'verbose_name': 'Master User',
                'verbose_name_plural': 'Master Users',
                'ordering': ['username'],
                'indexes': [models.Index(fields=['username'], name='master_mast_usernam_efa07b_idx'), models.Index(fields=['date_joined'], name='master_mast_date_jo_caa7d3_idx')],
            },
        ),
    ]
