# Generated by Django 4.2.24 on 2025-10-03 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the orbit', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'An orbit with this name already exists.'}, help_text='Required. 100 characters or fewer. Unique name for the orbit.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'Orbit name must be at least 3 characters long.'), django.core.validators.RegexValidator(message='Orbit name can only contain letters, numbers, spaces, hyphens, underscores, and dots.', regex='^[a-zA-Z0-9\\s\\-_\\.]+\\Z')], verbose_name='Orbit Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated)', max_length=110, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Optional. Brief description of the orbit (max 500 characters).', max_length=500, verbose_name='Description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', help_text='Current status of the orbit', max_length=10, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which orbits should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the orbit (e.g., #3B82F6)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(blank=True, help_text="Optional. Icon class name (e.g., 'fa-globe', 'bi-orbit')", max_length=50, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Orbit',
                'verbose_name_plural': 'Orbits',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrbitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('topic_count', models.PositiveIntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('orbit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='orbit.orbit')),
            ],
            options={
                'verbose_name': 'Orbit Statistics',
                'verbose_name_plural': 'Orbit Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['name'], name='orbit_orbit_name_628378_idx'),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['slug'], name='orbit_orbit_slug_0252d0_idx'),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['status'], name='orbit_orbit_status_6bfc61_idx'),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['order'], name='orbit_orbit_order_1e581f_idx'),
        ),
        migrations.AddIndex(
            model_name='orbit',
            index=models.Index(fields=['created_at'], name='orbit_orbit_created_8a56e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='orbit',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_orbit_name'),
        ),
        migrations.AddConstraint(
            model_name='orbit',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_orbit_slug'),
        ),
        migrations.CreateModel(
            name='ActiveOrbit',
            fields=[
            ],
            options={
                'verbose_name': 'Active Orbit',
                'verbose_name_plural': 'Active Orbits',
                'ordering': ['order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orbit.orbit',),
        ),
        migrations.CreateModel(
            name='ArchivedOrbit',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Orbit',
                'verbose_name_plural': 'Archived Orbits',
                'ordering': ['-updated_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orbit.orbit',),
        ),
    ]
