# Generated by Django 4.2.24 on 2025-10-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orbit', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a concise title for the topic (max 100 characters)', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the topic', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this topic is active and visible', verbose_name='Active')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated)', max_length=105, unique=True, verbose_name='Slug')),
                ('about', models.ForeignKey(help_text='The participant about we study', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='participant.participant', verbose_name='Participant')),
                ('orbit', models.ForeignKey(help_text='The Orbit where the topic belongs', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='orbit.orbit', verbose_name='Orbit')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Enter your question here', verbose_name='Question Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this question is active', verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which questions should be displayed', verbose_name='Order')),
                ('topic', models.ForeignKey(help_text='The topic this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topic.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Enter your answer here', verbose_name='Answer Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_correct', models.BooleanField(default=False, help_text='Designates whether this is the correct answer', verbose_name='Correct Answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which answers should be displayed', verbose_name='Order')),
                ('question', models.ForeignKey(help_text='The question this answer belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='topic.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created_at'], name='topic_topic_created_8bb90c_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['about', 'created_at'], name='topic_topic_about_i_6db5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='topic_topic_is_acti_423419_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('about', 'title'), name='unique_topic_per_participant'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'created_at'], name='topic_quest_topic_i_3b41c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='topic_quest_is_acti_f1599f_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'created_at'], name='topic_answe_questio_ca8142_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='topic_answe_is_corr_2fec9d_idx'),
        ),
    ]
