# Generated by Django 4.2.24 on 2025-10-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='studying_participants',
            field=models.ManyToManyField(blank=True, help_text='Participants who are studying about this participant', related_name='studying_topics', to='participant.participant', verbose_name='Studying Participants'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='about',
            field=models.ForeignKey(help_text='The participant about we study', on_delete=django.db.models.deletion.CASCADE, related_name='topics_about', to='participant.participant', verbose_name='Participant'),
        ),
    ]
