# Generated by Django 4.2.24 on 2025-10-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('topic', '0002_topic_studying_participants_alter_topic_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='bosses',
            field=models.ManyToManyField(blank=True, help_text='Participants who are bosses for this topic', related_name='boss_topics', to='participant.participant', verbose_name='Bosses'),
        ),
    ]
