# Generated by Django 4.2.24 on 2025-10-03 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('topic', '0003_topic_bosses'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='participant',
            field=models.ForeignKey(blank=True, help_text='Participant who provided this answer (leave blank for admin-generated answers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='participant.participant', verbose_name='Answered By'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['participant'], name='topic_answe_partici_3551da_idx'),
        ),
    ]
